export const initialTransactions = [
  {
    id: 'txn-1',
    date: '2026-01-03',
    label: 'Salary - Tech Corp',
    category: 'Salary',
    amount: 142000,
    type: 'income',
  },
  {
    id: 'txn-2',
    date: '2026-01-08',
    label: 'Blue Tokai Coffee',
    category: 'Food & Beverage',
    amount: 460,
    type: 'expense',
  },
  {
    id: 'txn-3',
    date: '2026-01-11',
    label: 'Rent - HSR Layout',
    category: 'Housing',
    amount: 32000,
    type: 'expense',
  },
  {
    id: 'txn-4',
    date: '2026-01-17',
    label: 'Freelance Gig',
    category: 'Consulting',
    amount: 28000,
    type: 'income',
  },
  {
    id: 'txn-5',
    date: '2026-01-26',
    label: 'Zomato Delivery',
    category: 'Food & Beverage',
    amount: 950,
    type: 'expense',
  },
  {
    id: 'txn-6',
    date: '2026-02-03',
    label: 'Salary - Tech Corp',
    category: 'Salary',
    amount: 142000,
    type: 'income',
  },
  {
    id: 'txn-7',
    date: '2026-02-07',
    label: 'Amazon Cloud Services',
    category: 'Subscriptions',
    amount: 5400,
    type: 'expense',
  },
  {
    id: 'txn-8',
    date: '2026-02-10',
    label: 'Urban Company',
    category: 'Home Services',
    amount: 1800,
    type: 'expense',
  },
  {
    id: 'txn-9',
    date: '2026-02-14',
    label: 'Stock Dividends',
    category: 'Investments',
    amount: 6400,
    type: 'income',
  },
  {
    id: 'txn-10',
    date: '2026-02-19',
    label: 'Blue Tokai Coffee',
    category: 'Food & Beverage',
    amount: 520,
    type: 'expense',
  },
  {
    id: 'txn-11',
    date: '2026-03-03',
    label: 'Salary - Tech Corp',
    category: 'Salary',
    amount: 142000,
    type: 'income',
  },
  {
    id: 'txn-12',
    date: '2026-03-05',
    label: 'Rent - HSR Layout',
    category: 'Housing',
    amount: 32000,
    type: 'expense',
  },
  {
    id: 'txn-13',
    date: '2026-03-12',
    label: 'Freelance Gig',
    category: 'Consulting',
    amount: 22000,
    type: 'income',
  },
  {
    id: 'txn-14',
    date: '2026-03-21',
    label: 'Zomato Delivery',
    category: 'Food & Beverage',
    amount: 870,
    type: 'expense',
  },
  {
    id: 'txn-15',
    date: '2026-03-24',
    label: 'Amazon Cloud Services',
    category: 'Subscriptions',
    amount: 5400,
    type: 'expense',
  },
];

export const defaultTransaction = {
  date: '2026-04-05',
  label: '',
  category: 'Salary',
  amount: '',
  type: 'expense',
};
